### ISSUE TITLE
force-deleting groups doesn't delete the servers in convergence

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1179]
Based on discussions, the tasks to do are:
- [ ] Set group status to DELETING on force delete: #1261
- [x] Return 404 on DELETING groups: #1268
- [x] Support `get_deleting` with status in `view_manifest` to use it in Converger: #1268
- [x] Converger deletes all servers for DELETING groups and then deletes the group: #1271 

- [ ] After force delete is fixed, remove 403 from the passing criteria list in the otter/integration/lib/autoscale.py delete_scaling_group() function (https://github.com/rackerlabs/otter/blob/lk_improve_catc6/otter/integration/lib/autoscale.py#L169)

Following is original comment from @radix:

Right now the way force-delete is implemented is

1. set desired to 0
2. kick off an asynchronous controller.converge()
3. delete the group

This works in the worker code because the worker code has everything it needs in-memory. With convergence, the second step above simply marks the group as dirty, and the converger comes along and tries to look up information about the group and can't find any, so it blows up, and the servers never get deleted.

One way to fix this would be to add a "DELETING" status to groups (and set desired to 0), and make it so force-delete sets that status. Then the converger would converge as normal, deleting everything, but then it would need to check the status and actually delete the group from Cassandra after it's done.

We considered making it so any time convergence got a `GroupNotFoundError`, it would just remove all the servers in the group, but that's "scary" from the perspective that there may be situations where a `GroupNotFoundError` is spuriously raised, likely after data loss, and we don't want to delete all the servers in that case.

**Comment by manishtomar** [comment]
To avoid deleting servers when spurious `GroupNotFoundError` is raised, say we decide to use ZK to store the fact the group is deleted and converger will delete all servers. What happens if there is ZK data loss for some reason?

**Comment by radix** [comment]
@manishtomar that's fine, I guess. Do you think that'd be preferable to using a DELETING status on the group? it would certainly be more consistent and reliable than using cassandra to store that flag...

And as far as data loss in ZK: a failure mode that *doesn't* delete all servers associated with a group seems good to me.

**Comment by manishtomar** [comment]
Yeah. I really like DELETING status. This is how it should've been from the beginning but you do realize that this is will be stored in CASS only. Also, the failure mode in this not bad. Converger will only delete if it sees this state. Any other time the servers will remain which is better than server being deleted :). 

The only question left is how to handle REST API. Should any API on group when it is DELETING return 404 or 410 (Gone) or 200 with this status but immutable. We might need to return 404 to remain consistent with any older clients.

**Comment by manishtomar** [comment]
I'll start working on this.

**Comment by cyli** [comment]
A hack was added in the trial integration tests to make cleanup not fail with a 403 (because cleanup force-deletes).

Once this is resolved, that should probably be fixed (see `otter/integration/lib/autoscale.py`)
