### ISSUE TITLE
Observer research todo list

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1441]
Either answer and document, or create separate issues for the following things:

- [x] will we use per-tenant or global cloud feeds for nova?
  - [x] If we use the per-tenant feeds, what frequency of requests can CF handle?
- [ ] can we usefully use the Cloud Feeds endpoint? What frequency of requests can they handle?
- [x] Does RCv3 have some sort of feed we can use to watch for events?
- [ ] How will we keep track of the "pointer" into the feed? do we need to keep track of it? Consider how this will interact with multiple observation nodes running.
- [ ] will be able to run multiple nodes of the observer?
- [ ] can we use data from the observer to supply data to the gatherer process, through a cache?

**Comment by wirehead** [comment]
From CF: "If you're going to be wanting to see multiple users' events (or if you'll want to see any private events/attributes), then I think the service-admin approach is definitely the way to go."

**Comment by wirehead** [comment]
http://docs-internal.rackspace.com/cloud-feeds/api/v1.0/feeds-devguide/content/Bestpracticesforconsumers.html

The best practice is to keep track of the last UUID read as a "pointer".

**Comment by radix** [comment]
I updated the link in your comment to point at the public docs.

**Comment by radix** [comment]
Okay, so I figure since we can use the global feed, we'll just store the last UUID read in zookeeper.

**Comment by radix** [comment]
It'd be great if we could have our gathering process get all of its data from a cache populated by the observer. We'll need to determine if the feeds have enough data to do this, and whether the feeds are actually reliable enough to do this in practice.

**Comment by radix** [comment]
Warning: I wrote a novel

We could just run one observer, but:

- that would be a single point of failure.
- it would require creating a new type of deployment for the observer, instead of just running it in the converger nodes

Most of our stuff is distributed, mainly giving us the benefit of reliability in the face of certain  network partitions (including node downtime, such as from mandatory restarts, which we can roll in the case of our multi-node deployments).

So it'd sure be nice if we could run multiple observers, too.

We could do an A/B deployment, requiring us to manually swap over to another node when one of them becomes inaccessible or goes down. We could also automate this with something like corosync, which is kind of horrible and would take even more operations work.

So what's the behavior we want, and what behavior do we want to avoid?

What would happen if we just run multiple observers, all using the same zookeeper node to keep track of the most recent CF event?

Without any other partitioning, they would cause duplicate notifications that groups need convergence -- each node would see some event relevant to a group, and they would all mark a group dirty. Fortunately, we have deduplication in the converger, so that all events before the start of convergence are treated as only one, so this might not actually be much of a problem. However, it could still cause extra convergence cycles, but probably very rarely.

First, some background: the nature of our convergence code is that almost any operation requires at least two convergence iterations -- one to perform some operation, like deleting a server, and another to check that it has been done and update our knowledge of the world. Given this, receiving multiple convergence requests very close together in time would very rarely cause more work than is usually performed.

If there are many convergence operations that don't actually result in some change to the world (I really don't know if this will be the case), then we could end up with two gatherings where one would suffice, in a case like this:

- observer A, B, and C all notice the same event relevant to a group
- A marks group dirty
- converger picks this up immediately, since it has a ZK child watch
- converger starts gathering
- B and C mark the same group dirty (bumping its version)
- converger finishes gathering and notices nothing happened, attempts to mark group clean, but can't since B and C have since updated the version of the dirty flag
- converger regathers

This isn't the end of the world, and in fact it's a good baseline. If we want to improve on this, we can do it with simple solutions that don't necessarily solve this problem 100%, because in worst cases we only do a bit of extra work without causing any terrible harm. So, assuming we do want to avoid some of these duplicate convergence requests, what _can_ we do to make this less likely?

When running multiple observers, we can allow only one of them to actually observe and emit events at a time. We can do this by using Corosync, which is kind of horrible, or we can do this by using ZooKeeper and the "election" recipe, provided by Kazoo, which is less horrible because we already interact with ZK in the observer. If the recipe works as described, only one leader should be active at a time. This basically allows us to survive network partitions wherein an observer node loses contact with ZooKeeper. But there are other network partition cases this _doesn't_ solve, like when an observer node loses contact with CF. In a perfect distributed system, other nodes (that still have contact with CF) would be able to take over the work of an observer node that loses contact with CF.

There are other use cases for the observer that involve it sending REST requests to third-party services (e.g. Heat). This leader-election solution also means that this node can't survive network partitions with the third-party system, where again it'd be nice if it we could. But for Otter's use case, we can live with this form of hot failover.


**My conclusions:**

- We could actually probably just run multiple observers and not worry about them causing duplicate events. They would probably very rarely cause extra work, and wouldn't cause any outright terrible problems, because of the way we've already set up convergence to avoid duplicate work.
- We can be extra careful by only allowing one node to actually observe at a time by using leader election.

**Comment by cyli** [comment]
Random comment - if we do go with only allowing one node to actually observe at a time, can we handle CF partitions by just having the leader drop from the group for a time if it can't connect to CF?  Then someone else can take over?  Not super important - as you said, it seems fine just to leave as it.

**Comment by radix** [comment]
oh, @cyli, you make a great point. that does seem like it'd work.

**Comment by radix** [comment]
uh woops didn't mean to close this

**Comment by radix** [comment]
# Optimizing gathering with a CF-populated cache

If we can trust CF to deliver messages and we can trust that Nova populates CF reliably, we may be able to reduce the amount of "gathering" we do -- that is, reduce the number of requests to nova to learn the state of the world.

The general idea is this: (within some threshold of time, say, an hour or a day), if we have a baseline of data from a "gather the world" run, we can update that data with events from cloud feeds. Then, upon gathering data for convergence, we simply consult the cached-and-updated data for the state of the world, instead of going after nova.

The big question, of course, is where this data should be stored. We could put it into Cassandra, though I think we've learned that mutating data in Cassandra (that we actually rely on) is a bad idea due to inconsistency problems. ZooKeeper is probably a bad idea for such high-scale data storage (not that it's particularly high scale, it's just that usually ZK is good for things like small consistent pointers, not actual data storage.

Typically things like Memcached or Redis are used for these applications. Rackspace provides a [Redis to Go](http://redistogo.com/) service, so that's certainly an option -- while it wouldn't completely remove the operational burden of running Otter, it's probably better than maintaining our own Redis instance.

Why would we actually need a third-party service? The main reason is because the observer is likely to be running separate from the converger, and needs to be able to update that data. Otherwise we could just keep a local in-memory cache on the converger nodes, especially since they already partition workload by tenant -- a converger gathering data for a tenant will stay responsible for that tenant until a repartitioning due to some Converger node being introduced or disappearing. There _may_ be designs of the Observer that run it in-process with the Converger *and* guarantee that they only process events for the same tenants that the node is converging, but that's not our current working design ([above](https://github.com/rackerlabs/otter/issues/1441#issuecomment-102145657)).

So, Redis: This would be a decent amount of code to write. **We'd need to implement**:

- Converger: dumping the data into Redis after each full-gather
- Converger: setting up the data to be garbage collected after a time, probably with [EXPIRE](http://redis.io/commands/expire)
- Converger: reading and using that data when it's available, instead of doing a full-gather
- Observer: updating that data from Cloud Feeds events
- anything else I've forgotten (comments welcome)

I think before we decide to do this **we should determine**:

- just how much this will help Nova. Consider especially use cases where thousands of servers are being asked to scale up, and how much IO that involves with Nova.
- how much resident data this will require, since we'll need to know how big of an instance to get: http://redistogo.com/
