### ISSUE TITLE
RackConnect v3.0 load balancer management

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#739]
RCv3 should be supported, both in our current job-oriented code, and in the future convergence-oriented code.
# Requirements
## Adding nodes to load balancers

Problems:
- RCv3 uses only node ids. CLB uses IPs and ports.
- RCv3 does not support some CLB features, such as draining and weights.
- RCv3 supports bulk (n nodes x n LBs) requests; CLB does not have such an API.

These differences make it difficult to support both with similar APIs.
## Removing nodes from load balancers

This is a bit easier than adding nodes to load balancers, because CLB and RCv3 support essentially the same API. However, a lot of code assumes that it will always be CLB. Therefore, it is necessary to teach some code to accept generic load balancer configurations.
# Desired outcome

Support RCv3-style load balancers.

As a side effect of touching a bunch of this code, it will be more flexible in the future when some other load balancing technology comes along.

As a side effect of putting a lot of the convergence machinery to work for the first time, a significant portion of work will also be completed towards that goal.
# Implementation plan

In order to minimize the amount of duplicate work, these features will be implemented as if they were convergence features (using `IStep`, pure HTTP, effect...).
# Progress
## Support RCv3 in worker code

This will have to solve more problems, partially because it's the first RCv3-supporting codebase and partially because it made very deep assumptions about CLB being the only LB API.
- [x] Implement schema: #734.
- [x] Implement RCv3 ISteps: #728.
- [x] Implement enough IStep -> request generation stuff: #736, #758, #759
- Fix parts of job code that assume CLB:
  - [x] #737
  - [x] #738
- [x] Add `"rackconnect"` configurable service name to config, just like e.g. `"cloudLoadBalancers"`: #784
- [x] Clarify that CLB-specific code paths are CLB-specific: #742.
- [x] Move `endpoints`, `public_endpoint_url` from `otter.worker.launch_server_v1` to `auth`. This is necessary because `convergence` imports them from `launch_server_v1`; now that `launch_server_v1` also wants pieces of `convergence` (steps, requests...), that introduces a circular import. #768
- [x] Pass in a _real_ request_fn that actually works instead of just being a vehicle for auth-related arguments: #770 
- [x] Implement alternate code path for LB adding that uses new adding step (depends on #728, #737). This will involve implementing an alternative `add_to_clb` (but using RCv3 instead), and then using that code path in `add_to_load_balancer` depending on the LB type. #751, #754, #756, #763, #772 
- [x] Implement alternate code path for LB removal that uses new removal step (depends on #728, #738). This will involve moving most of `remove_from_load_balancer` into a new function, `_remove_from_clb`, then implementing a new alternative code path `_remove_from_rcv3` that relies on the IStep from #728, and then picking the appropriate path. #754, #756, #773 
## Functional tests

This is being managed in #793.
