### ISSUE TITLE
More powerful success predicate for convergence.steps.Request

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#824]
Currently, `convergence.steps.Request` only has one way to check if a request was successful or not: response codes. This is not always good enough. For example, when deleting a node from a RCv3 load balancer pool, `409 Conflict` can mean that the pool is inactive, or that the node doesn't exist. The former is probably an error condition, the latter means that we've successfully deleted the node (kind of).

It is probably worth noting that there's a reason it isn't good enough: it was added as a stopgap solution in order to make RCv3 work, and not part of the original API. It was added because it was the thing we could make work right now, not because it was necessarily any good.

I'm suggesting that instead of success codes, we allow specifying an arbitrary callable of `Response -> bool`. This can replace `success_codes` by also introducing a little helper function, `success_codes` (`has_success_code`?), so that:

```
success_codes=(204,)
```

becomes

```
is_successful=has_status_code(204)
```

... or something. Such response predicates can be joined with `otter.util.fp.predicate_all`.

Unfortunately, `otter.util.http.check_success` is quite old, and used all over the place. Its name doesn't really suggest that it relies on codes only. It probably isn't going away. However, we can implement it in terms of the generic API as described above.

Resolving this allows us to resolve #820 for both convergence and worker code in one fell swoop, in addition to giving us more expressive power.

- [x] Write a predicate for status codes: #832
- [x] Write a predicate checker to replace `check status`: #833
- [x] Change `add_error_handling` to use a predicate rather than status codes: #834 
- [x] Make equal preds compare equal: #845
- [x] Change `service_request` (inside `get_request_func`) to take a predicate rather than status codes, and change all call sites of `request_func` too. #835
- [x] Change convergence steps to actually produce success preds instead of just success codes. #870
- [x] Remove the old status code thing that `add_error_handling` used to use (`check_status`). #876

**Comment by lvh** [comment]
All PRs are merged, so this issue can be closed.
