### ISSUE TITLE
Publish AS actions in cloud feeds

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#838]
otter should publish actions it takes on behalf of tenant in cloud feeds. This includes errors too. This is large task that can be broken down into:
- [x] Design schema and get it pushed (https://github.com/rackerlabs/standard-usage-schemas/pull/419)
- [x] Get identity service admin role to push events
      - [x] https://jira.rax.io/browse/NEB-508 - staging completed
      - [x] https://jira.rax.io/browse/CCM-711 - production
- [x] Structure code to push messages in cloud feed - #966 
- [x] Test feeds with staging by putting extra DC field #1108
- [x] Setup structured formal logging #1107
- [x] Design list of messages to be published: #1109
- [x] Start logging #884

**Comment by manishtomar** [comment]
Here is possible list of messages I am thinking of:
- At the end of convergence cycle when it is going to execute the plan. The idea is to describe the actions in short readable format, i.e. combine multiple steps into one single message.
  - Launching x servers
  - Deleting x servers
  - Adding x servers to CLB <id>
  - Removing x servers from CLB <id> 
  - Going to drain node <id> with ip <ip>
- When group's status is changed:
  - Group's status is changed to ERROR due to <error>
  - Group's status is changed to ACTIVE
- During hard errors?
  - When executing convergence it is possible that a particular step execution fails after some amount of retries. Should this error be propagated since convergence might be kicked again after sometime? 
- When executing policy
  - Executing policy <id>: changed desired from <old> to <new>. In case of scheduled policy execution, `scheduleTime` attribute will contain the timestamp of when the policy execution (that should ideally be as close to event time as possible)  
- When configuration changes
  - Launch configuration changed
  - Group configuration changed (could be min/max/cooldown)

**Comment by radix** [comment]
There are potentially other things under "When configuration changes", such as "policy CRUD", "webhook CRUD"

**Comment by lvh** [comment]
I think it makes a lot of sense to combine these efforts with https://github.com/rackerlabs/otter/issues/884. While you may not want to push every logged message to Cloud Feeds, the set of things you want to push to Cloud Feeds is almost certainly a subset of the things you want to log. Furthermore, the log and Cloud Feeds have similar concerns regarding reporting: you don't want to just report the repr of a list of 500 identical `CreateServer` objects.

**Comment by lvh** [comment]
As always when designing things, it's important to know who you're designing for, and how you expect them to use it. I think we probably all have a similar idea, but just in case...

There's three levels of errors:

1. A single request failed, but is still being retried. No-one thinks these should be logged.
2. A single request failed, despite retries. Most people think these shouldn't be logged, but there's some gray area. 
3. The group is hard-wedged, and we're giving up. Everyone thinks these should be logged (with a reason why).

If this feed is strictly informational, logging the intermediary error level makes little sense.

If this feed is used as an audit/debugging tool, it does make sense to log the intermediary; there's a difference between otter failing and an upstream service failing. This isn't just useful for developers doing metrics; knowing what kind of failures occur and why can also help support provide better service levels to customers, by e.g. suggesting different server flavors, regions, images...

Finally, despite that nobody wants a noisy line, it's easier to throw information away than it is to conjure it.

**Comment by lvh** [comment]
Oh, and as a final note re: throwing data away; if this does end up being very relevant, there's always category-based querying.

**Comment by manishtomar** [comment]
Created ticket https://jira.rax.io/browse/NEB-508 to request `cloudfeeds:service-admin` role.

**Comment by cyli** [comment]
Closing this in favor of all the other CF tickets.
