### ISSUE TITLE
AS A developer I WANT to run tests in parallel SO THAT we make tests more appealing to run by individual engineers.

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#841]
- [ ] Identify all variations of tests
- [ ] Which tests can and cannot be run in parallel?
- [ ] How do we handle parallel-run Jenkins tasks that fail?
- [ ] Pranav, can you edit this ticket to fill in what I'm missing?
