### ISSUE TITLE
Improve automated code quality tools

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#871]
Our automated code quality checking is less than perfect:
- The lint standards are underspecified, so it's not clear what "lint" is.
- We're not using the best tooling available. 
- The tooling we use is outdated.

Furthermore:
- We don't check code coverage as part of our CI process.
- We don't check docstrings for quality at all.

Fixing this requires several steps:
- [x] Make a CONTRIBUTING.md that's unambiguous about which standards we follow: #914
- [x] Use flake8 + flake8-import-order: #877 + #906
- [ ] Use pep8-naming: #907
- [x] Check if packages are outdated as part of the linting process (shouldn't fail the build) (#877)
- [x] Fail on reduced test coverage. The easiest way to do this actually probably involves waiting until we run the tests on Travis with Mimic, and then using coveralls or something.
- [ ] Use doc8 + pep257 + sphinx-build + sphinxcontrib-spelling + pyechant (this means Sphinx docs with all the API docs in it). Alternatively: pylint; although apparently that's not smart enough to know about docstring standards.
