### ISSUE TITLE
Remove deleted server's nodes from LBs

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#881]
Convergence should remove any out-of-band deleted servers from all the LBs it was attached to. This requires getting deleted servers from `get_scaling_group_servers` which needs time since it was last fetched. [Docs](http://docs.rackspace.com/servers/api/v2/cs-devguide/content/ChangesSince.html) for this. Otherwise Nova will return all servers deleted in last 30 days. It is not clear where this state will be stored. It would most likely be otter db. So, this task can be divided in:

UPDATE 05/22: Based on discussion below following tasks:
- [x] Server cache model changes
- [x] Convergence gathering from cache if it exists (updating if it doesn't)
- [x] Deleting old cache after convergence succeeds
- [ ] Heuristic check for CLB IP reuse: Check 2nd point of https://github.com/rackerlabs/otter/issues/881#issuecomment-102537953
- [x] Add `changes_since` support in mimic: https://github.com/rackerlabs/mimic/issues/252
- [x] Add support to get deleted servers in `get_server_details` and `get_scaling_group_servers`: #1252
- [x] Change `converge` to remove dangling LB nodes

**Comment by cyli** [comment]
Discussion from Slack:

We probably don't need to store any server data, we just don't update the last-fetched date until we have successfully cleaned up all the nodes from the LB. 

We can probably do other optimizations to that date too.

There is a possibility that (especially the farther back the server was deleted) the IP from that server has been reused, and cleaning that IP off of a CLB will result in removing a currently valid server from the CLB.

We should ask how long it is before servicenet addresses are re-used.

**Comment by cyli** [comment]
Also, this may not be testable in Mimic is because Mimic does not support changes-since yet.

**Comment by cyli** [comment]
@manishtomar and @wirehead and I were discussing this today, and a couple of things came out of the discussion:

1.  @manishtomar suggested a solution that means we don't have to do any fancy figuring out of which servers have been cleaned up and which have yet to be cleaned up:
    1.  A convergence cycle starts, and we gather any deleted servers since time T=0.  The gathering happens at time T=1.
    2.  If any of those servers are still attached to any load balancers, this convergence cycle will attempt to remove them.
    3.  Hence if the convergence cycle succeeds at time T=2, that means that the load balancer nodes were all removed successfully (or that the server was not on any load balancers to begin with), and so we can record T=1 the last fetched time.
    4.  If the convergence cycle needs to retry for any reason, we do not change the last fetched time.  (It doesn't matter whether it failed for some other reason - it just means we check again next time.)  If the convergence cycle fails, we again do not change the last fetched time.

2.  We discussed a heuristic we use to be more confident that the IP was not re-used, even if the server was deleted 30 days ago.
    1. When we see a deleted server, we check the time it was deleted (probably the last changed date in the server details JSON).
    2. If we discover its IP is on a CLB, we check the create time of the corresponding node.  If it was at or before the server delete, we can be reasonably sure the node was created for this server, and clean it up.  We can even remove the node if the node creation time was the server deletion time, so long as the time difference is small (way before the IP recycle period).  Otherwise, we don't touch the node.

3.  @wirehead suggests that the recycle period for servicenet IPs (which is all we care about for CLBs) is pretty long, since there are a lot of servicenet IPs.

**Comment by radix** [comment]
I'm pretty sure I've now read and understood all four points in your comment, @cyli, and they make sense.

With #4 I'm a little bit concerned about storing the data in Cass; is there an idea about what the schema would look like for this table, and how we would garbage collect the old data?

I guess if we actually do the Redis-based caching that I described in #1441 we could put all the data in Redis, but I think we can put off this decision for a little bit -- the points 1 through 3 are all perfectly agreeable to me, and #4 makes a lot of sense.

**Comment by manishtomar** [comment]
> is there an idea about what the schema would look like for this table

```CREATE TABLE servers_cache(
tenant_id ascii, group_id ascii, changes_since timestamp, server_id ascii, ... <other server fields>,
PRIMARY KEY ((tenant_id, group_id, changes_since), server_id)
```
This will be filled first time when getting servers from nova. The `changes_since` will be the time when the servers were fetched. This (changes_since) will also be stored in group state. The TTL on the servers can be 1-2 weeks. Next time onwards, only changes can be fetched based on changes_since and all servers can be got by merging this cache with changes received.

Here, you can notice extra bracket between tenant, group and changes_since. This just ensures that combination of all 3 will be partition key ensuring there is equal distribution of cache in the cluster since we will always fetch knowing these 3 fields. The disadvantage of this that you can't get servers of a particular tenant or group which we probably don't need. This is not important. Something that we can keep in mind :)

> and how we would garbage collect the old data?

This is age old computer science question. When does the cache gets invalidated? In our case, it could be observer. Until then, we can just have some timeframe say 2 weeks. If convergence kicks in after cache is deleted, then it will just fetch all the servers.

**Comment by cyli** [comment]
With the changes-since parameter as part of the key, it looks like this is all append-only.  Could you elaborate on the merge process some more?  Is gathering going to:

1.  get changes-since
2.  insert all changes-since events into cass
3.  select * from servers_cache where tenant_id=... and group_id=...
4.  do a merge of all history?

As part of the merge process will there be any checkpointing (e.g. store some merged data so we don't have to read all history, and if so how are we going to do that/delete old data?)

**Comment by radix** [comment]
@cyli The idea is not to store the *events* in cass, but rather the "model" which has been calculated based on the events. so, you get changes-since, you query the event feed, you walk through each event and apply the change to your model, then you save the model into cass. 


@manishtomar: I'm no talking about cache invalidating so much as simply deleting already-invalidated data -- when we append a row with a higher changes-since, that by itself is an indication that the older rows are invalid. But we still need to *delete* those older rows. It would probably be easy enough to just delete old rows while we're inserting the new one, but given cassandra's consistency model I *think* that would mean clients could possibly observe a state where there are no rows, given that our timestamps can go backwards...

Also, I'm not sure we need to have a new `changes-since` field in the group -- can't we just query for the highest one in the server cache table?

**Comment by cyli** [comment]
@radix:  Oh, ok, I see, so at any given point, `select * from servers_cache where tenant_id=... and group_id=... and changes_since=<thing from the state table>` would always give you the current state of the world, which you'd merge with `changes_since`, and then you'd write the new merged state of the world under the new `changes-since` timestamp?

Would we only then write to the cache after the convergence cycle ends?  Thus not updating there was some issue cleaning up deleted servers, because of point #1 in https://github.com/rackerlabs/otter/issues/881#issuecomment-102537953?

**Comment by manishtomar** [comment]
I am thinking of renaming `changes_since` in the schema and state to be `last_fetched` since it makes more sense from storage perspective. `changes_since` makes sense when fetching.

@radix:

> It would probably be easy enough to just delete old rows while we're inserting the new one

+1

> but given cassandra's consistency model I think that would mean clients could possibly observe a state where there are no rows, given that our timestamps can go backwards...

The chances of that happening should be less because gathering and insertion of the cache happens on a single node with minimal of 10s delay. Even otherwise, if gathering does not find the cache at `last_fetched` time, it will just fetch all of Nova and update the cache with current time. 

> Also, I'm not sure we need to have a new changes-since field in the group -- can't we just query for the highest one in the server cache table?

With this schema no. To do that, the schema could be `PRIMARY KEY ((tenant_id, group_id), last_fetched, server_id)`. Here, you will have to query all servers of a particular group using `tenant_id=.. AND group_id=...` sorted (DESC) based on `last_fetched`. The key thing is `last_fetched` needs to be part of primary key to use that as part of the query. I am sorry I didn't get your intention with this comment. Did you mean to say that we wouldn't need to store `last_fetched` in state if we do this since we can always take latest `last_fetched` time and use that in `changes_since`?

@cyli 

> and then you'd write the new merged state of the world under the new changes-since timestamp?

Exactly! You explained it better than I did :)

> Would we only then write to the cache after the convergence cycle ends? Thus not updating there was some issue cleaning up deleted servers, because of point #1 in #881 (comment)?

Yes. I hadn't thought of this but it makes sense.

**Comment by radix** [comment]
> @radix said
> > Also, I'm not sure we need to have a new changes-since field in the group -- can't we just query for the highest one in the server cache table?

@manishtomar said
> With this schema no. To do that, the schema could be PRIMARY KEY ((tenant_id, group_id), last_fetched, server_id). Here, you will have to query all servers of a particular group using tenant_id=.. AND group_id=... sorted (DESC) based on last_fetched. The key thing is last_fetched needs to be part of primary key to use that as part of the query. I am sorry I didn't get your intention with this comment. Did you mean to say that we wouldn't need to store last_fetched in state if we do this since we can always take latest last_fetched time and use that in changes_since?

Yes, my goal is to avoid this mutable piece of data. It seems if we're regularly deleting old data it shouldn't be a problem to just query the server cache on (tenant_id, group_id).

From the discussion we had on slack: the primary key should probably be `((tenant_id, group_id), last_update_time, server_id)`. our *query* would only search for the right tenant_id and group_id. Then we would just look at whatever the highest last_update_time is from the results, and ignore any that are older.  This way we don't need to keep track of last_update_time separately in the group table. Make sense?

**Comment by manishtomar** [comment]
> Make sense?

Yes. Sounds like a good idea for now. I'll start working on this and let you know if I find anything uncomfortable.

**Comment by cyli** [comment]
This seems to be done except for #881, which can't be done any more since we're not using changes-since any more. 

I'm going to close this because I think that this issue has been dealt with, but please re-open if I got it wrong.
